using System.Globalization;

namespace LaTeXSnipper.OfficePlugin.WordAddIn;

public static class WordAddInText
{
    public static string Get(string key)
    {
        bool zh = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "zh";
        return zh ? GetZh(key) : GetEn(key);
    }

    private static string GetEn(string key)
    {
        return key switch
        {
            "RibbonTab" => "LaTeXSnipper",
            "FormulaGroup" => "Formula",
            "EditGroup" => "Edit",
            "NumberingGroup" => "Numbering",
            "ToolsGroup" => "Tools",
            "InsertInlineButton" => "Inline Formula",
            "InsertDisplayButton" => "Display Formula",
            "InsertNumberedButton" => "Numbered Formula",
            "ScreenshotOcrButton" => "Screenshot OCR",
            "CancelOcrButton" => "Cancel OCR",
            "AutoNumberButton" => "Auto Number",
            "RenumberButton" => "Renumber All",
            "HelpButton" => "Help",
            "SettingsButton" => "Settings",
            "ShowTaskPaneButton" => "Status Pane",
            "LoadSelectedButton" => "Load Selected",
            "DeleteSelectedButton" => "Delete Selected",
            "OfficePluginLabel" => "Office plugin",
            "EquationLabel" => "Equation",
            "DisplayOption" => "Display equation",
            "AutoNumberOption" => "Auto number",
            "ManualNumberPlaceholder" => "Custom number",
            "ConnectButton" => "Connect",
            "InsertInlineTip" => "Insert an inline Word equation.",
            "InsertDisplayTip" => "Insert a centered display equation.",
            "InsertNumberedTip" => "Insert a numbered display equation using the status pane setting.",
            "ScreenshotOcrTip" => "Wait for the next capture; click again to cancel.",
            "AutoNumberTip" => "Add automatic numbering to the selected formula.",
            "RenumberTip" => "Renumber all automatically numbered formulas in document order.",
            "HelpTip" => "Show Office plugin help.",
            "SettingsTip" => "Configure plugin shortcuts and numbering defaults.",
            "ShowTaskPaneTip" => "Show the status pane.",
            "LoadSelectedTip" => "Load the selected formula.",
            "DeleteSelectedTip" => "Delete the selected formula and its metadata.",
            "EditorInsert" => "Insert",
            "EditorUpdate" => "Update",
            "Cancel" => "Cancel",
            "ErrorTitle" => "LaTeXSnipper",
            "SelectedFormulaRequired" => "Select a formula first.",
            "SelectedFormulaMetadataMissing" => "The selected formula metadata could not be found.",
            "InsertInsideFormulaError" => "Place the cursor outside the formula before inserting another formula.",
            "InsertInsideNumberedFormulaError" => "Place the cursor outside the formula before inserting another formula.",
            "TaskPaneTitle" => "LaTeXSnipper",
            "TaskPaneActions" => "Actions",
            "ReadyStatus" => "Ready.",
            "WorkingStatus" => "Working...",
            "EditorReadyStatus" => "Editor ready.",
            "ConvertingStatus" => "Converting LaTeX through the desktop Bridge.",
            "OleInsertingStatus" => "Inserting LaTeXSnipper OLE formula object.",
            "CommandTimeoutStatus" => "Office command timed out. The document was left unchanged if the operation had not reached Word yet.",
            "InsertedStatus" => "Inserted equation into Word.",
            "UpdatedStatus" => "Updated equation in Word.",
            "UnchangedStatus" => "Equation unchanged.",
            "DeletedStatus" => "Deleted selected equation.",
            "LoadedStatus" => "Loaded selected equation.",
            "OcrWaitingStatus" => "Waiting for screenshot OCR.",
            "OcrRecognizingStatus" => "Recognizing screenshot formula.",
            "OcrCanceledStatus" => "Screenshot OCR canceled.",
            "OcrLoadedStatus" => "Screenshot OCR result loaded.",
            "AutoNumberedStatus" => "Added automatic numbering to selected equation.",
            "RenumberedStatus" => "Renumbered {count} equations.",
            "NoNumberedStatus" => "No automatically numbered equations found.",
            "AlreadyNumberedStatus" => "Selected equation already has numbering.",
            "AutoNumberDisplayOnlyStatus" => "Automatic numbering only applies to unnumbered display equations.",
            "EditingFormulaTitle" => "Editing Formula",
            "HelpStatus" => "Help opened.",
            "SettingsStatus" => "Settings opened.",
            "SettingsTitle" => "LaTeXSnipper Office Plugin Settings",
            "SettingsNumberingGroup" => "Default numbered formula layout",
            "SettingsNumberRight" => "Number on the right",
            "SettingsNumberLeft" => "Number on the left",
            "TaskPaneShownStatus" => "Status pane shown.",
            "ConnectedBridgeStatus" => "Connected to LaTeXSnipper.",
            "BridgeOcrAlreadyWaiting" => "Screenshot OCR is busy. Wait a moment and try again.",
            _ => key,
        };
    }

    private static string GetZh(string key)
    {
        return key switch
        {
            "RibbonTab" => "LaTeXSnipper",
            "FormulaGroup" => "公式",
            "EditGroup" => "编辑",
            "NumberingGroup" => "编号",
            "ToolsGroup" => "工具",
            "InsertInlineButton" => "行内公式",
            "InsertDisplayButton" => "行间公式",
            "InsertNumberedButton" => "带编号公式",
            "ScreenshotOcrButton" => "截图识别",
            "CancelOcrButton" => "取消识别",
            "AutoNumberButton" => "自动编号",
            "RenumberButton" => "重编号",
            "HelpButton" => "帮助",
            "SettingsButton" => "设置",
            "ShowTaskPaneButton" => "状态窗格",
            "LoadSelectedButton" => "加载所选",
            "DeleteSelectedButton" => "删除所选",
            "OfficePluginLabel" => "Office 插件",
            "EquationLabel" => "公式",
            "DisplayOption" => "行间公式",
            "AutoNumberOption" => "自动编号",
            "ManualNumberPlaceholder" => "自定义编号",
            "ConnectButton" => "连接",
            "InsertInlineTip" => "插入行内公式。",
            "InsertDisplayTip" => "插入行间公式。",
            "InsertNumberedTip" => "按状态窗格编号设置插入带编号公式。",
            "ScreenshotOcrTip" => "等待下一次截图；再次点击可取消。",
            "AutoNumberTip" => "为选中的公式自动添加编号。",
            "RenumberTip" => "重排所有自动编号的公式。",
            "HelpTip" => "显示插件帮助。",
            "SettingsTip" => "配置插件各项设置。",
            "ShowTaskPaneTip" => "显示状态窗格。",
            "LoadSelectedTip" => "加载选中的公式。",
            "DeleteSelectedTip" => "删除选中的公式及其元数据。",
            "EditorInsert" => "插入",
            "EditorUpdate" => "更新",
            "Cancel" => "取消",
            "ErrorTitle" => "LaTeXSnipper",
            "SelectedFormulaRequired" => "请先选择一个 LaTeXSnipper 公式。",
            "SelectedFormulaMetadataMissing" => "无法找到所选公式的元数据。",
            "InsertInsideFormulaError" => "请将光标移到公式外，再插入其他公式。",
            "InsertInsideNumberedFormulaError" => "请将光标移到公式外，再插入其他公式。",
            "TaskPaneTitle" => "LaTeXSnipper",
            "TaskPaneActions" => "操作",
            "ReadyStatus" => "就绪。",
            "WorkingStatus" => "处理中...",
            "EditorReadyStatus" => "编辑器已就绪。",
            "ConvertingStatus" => "正在通过桌面端 Bridge 转换 LaTeX。",
            "OleInsertingStatus" => "正在插入 LaTeXSnipper OLE 公式对象。",
            "CommandTimeoutStatus" => "Office 命令超时。若操作尚未写入 Word，文档已保持不变。",
            "InsertedStatus" => "已将公式插入 Word。",
            "UpdatedStatus" => "已更新 Word 公式。",
            "UnchangedStatus" => "公式未更改。",
            "DeletedStatus" => "已删除所选公式。",
            "LoadedStatus" => "已加载所选公式。",
            "OcrWaitingStatus" => "正在等待截图识别；请使用全局快捷键后框选公式区域。",
            "OcrRecognizingStatus" => "正在识别截图公式。",
            "OcrCanceledStatus" => "已取消截图识别。",
            "OcrLoadedStatus" => "截图识别结果已加载。",
            "AutoNumberedStatus" => "已为所选公式添加自动编号。",
            "RenumberedStatus" => "已重排 {count} 个公式编号。",
            "NoNumberedStatus" => "未找到自动编号公式。",
            "AlreadyNumberedStatus" => "所选公式已有编号。",
            "AutoNumberDisplayOnlyStatus" => "自动编号只适用于未编号的行间公式。",
            "EditingFormulaTitle" => "正在编辑公式",
            "HelpStatus" => "已打开帮助。",
            "SettingsStatus" => "已打开设置。",
            "SettingsTitle" => "LaTeXSnipper Office 插件设置",
            "SettingsNumberingGroup" => "带编号公式默认布局",
            "SettingsNumberRight" => "编号在右侧",
            "SettingsNumberLeft" => "编号在左侧",
            "TaskPaneShownStatus" => "状态窗格已显示。",
            "ConnectedBridgeStatus" => "已连接到 LaTeXSnipper。",
            "BridgeOcrAlreadyWaiting" => "截图识别正忙，请稍后再试。",
            _ => key,
        };
    }
}
